#+TITLE: Play with the kernel lab
#+AUTHOR: Junbo Luo
#+OPTIONS: toc:nil num:nil
#+SETUPFILE: theme-readtheorg.setup

** Reference
- http://coffeenix.net/doc/kernel/startup.html/x72.html#START-KERNEL--FIG
- https://medium.com/@boutnaru/linux-kernel-task-struct-829f51d97275
- https://elixir.bootlin.com/linux/v6.2-rc1/source/include/linux/sched.h#L737
- https://www.stackscale.com/blog/inodes-linux/#Metadata_stored_in_an_inode
- https://man7.org/linux/man-pages/man2/fork.2.html
- https://en.wikipedia.org/wiki/Unistd.h
- https://github.com/torvalds/linux/blob/master/arch/x86/entry/entry_64.S
- https://github.com/torvalds/linux/blob/master/kernel/printk/printk.c
- man pahole
- http://coffeenix.net/doc/kernel/startup.html/x332.html

** Answer the questions

*** start_kernel();

It orchestrates all of Linux's startup procedure

*** init();

It completes the kernel's boot process by calling do_basic_setup() to initialize the kernel's PCI and network features. The remaining memory allocated for initialization is discarded, scheduling is enabled, the standard input, output and error streams are created 

*** struct task_struct;

“task_struct” holds the data an operating system needs about a specific process.
Among those data elements are: credentials ,priority, PID (process ID), PPID (parent process ID), list of open resources, memory space range information, namespace information

*** struct inode;

It stores information about a file or directory.Inodes contain metadata about the file or directory, including:
- File type
- File size
- Owner ID
- Group ID
- Read, write and execute permissions
- Last access time
- Last change time
- Last modification time

*** struct file;

It plays a crucial role in managing open files, file operations, and file I/O.

*** fork();

It creates a new process by duplicating the calling process.

*** include/asm-generic/unistd.h

It is the name of the header file that provides access to the POSIX operating system API.

*** arch/x86_64/entry.S

It contains the system-call and fault low-level handling routines.

*** kernel/printk.c

Modified to make sys_syslog() more flexible.
